version: '3.5'

services:
  nemon-web:
    container_name: nemon-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 251:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - nemon-be
    networks:
      - nemon-network

  nemon-be:
    container_name: nemon-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=nemon
    volumes:
      - ./:/appdata/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - nemon-network
networks:
  nemon-network:
    external: true
